name: package

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string

jobs:
  package:
    name: "package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: package-Docker
      run: |
        docker login http://ghcr.io -u EPI-DAT-902 -p ${{ secrets.TOKEN_DAT_FOR_PACKAGES }}
        docker build --file Dockerfile -t ghcr.io/EPI-DAT-902/dat-902:latest .
        docker push ghcr.io/EPI-DAT-902/dat-902:latest